/* This file is generated by scripts/migrate_assets_to_cloudinary.py. */
export const cloudinaryAssets = {
  "/images/arrival-1-model.png": "https://res.cloudinary.com/sguhbpc0/image/upload/f_auto,q_auto/v1/isole-digital-showroom/arrival-1-model",
  "/images/arrival-1-product.png": "https://res.cloudinary.com/sguhbpc0/image/upload/f_auto,q_auto/v1/isole-digital-showroom/arrival-1-product",
  "/images/arrival-2-model.png": "https://res.cloudinary.com/sguhbpc0/image/upload/f_auto,q_auto/v1/isole-digital-showroom/arrival-2-model",
  "/images/arrival-2-product.png": "https://res.cloudinary.com/sguhbpc0/image/upload/f_auto,q_auto/v1/isole-digital-showroom/arrival-2-product",
  "/images/arrival-3-model.png": "https://res.cloudinary.com/sguhbpc0/image/upload/f_auto,q_auto/v1/isole-digital-showroom/arrival-3-model",
  "/images/arrival-3-product.png": "https://res.cloudinary.com/sguhbpc0/image/upload/f_auto,q_auto/v1/isole-digital-showroom/arrival-3-product",
  "/images/collection-1.png": "https://res.cloudinary.com/sguhbpc0/image/upload/f_auto,q_auto/v1/isole-digital-showroom/collection-1",
  "/images/collection-2.png": "https://res.cloudinary.com/sguhbpc0/image/upload/f_auto,q_auto/v1/isole-digital-showroom/collection-2",
  "/images/collection-3.png": "https://res.cloudinary.com/sguhbpc0/image/upload/f_auto,q_auto/v1/isole-digital-showroom/collection-3",
  "/images/collection-4.png": "https://res.cloudinary.com/sguhbpc0/image/upload/f_auto,q_auto/v1/isole-digital-showroom/collection-4",
  "/images/community-1.png": "https://res.cloudinary.com/sguhbpc0/image/upload/f_auto,q_auto/v1/isole-digital-showroom/community-1",
  "/images/community-2.png": "https://res.cloudinary.com/sguhbpc0/image/upload/f_auto,q_auto/v1/isole-digital-showroom/community-2",
  "/images/community-3.png": "https://res.cloudinary.com/sguhbpc0/image/upload/f_auto,q_auto/v1/isole-digital-showroom/community-3",
  "/images/community-4.png": "https://res.cloudinary.com/sguhbpc0/image/upload/f_auto,q_auto/v1/isole-digital-showroom/community-4",
  "/images/community-5.png": "https://res.cloudinary.com/sguhbpc0/image/upload/f_auto,q_auto/v1/isole-digital-showroom/community-5",
  "/images/community-6.png": "https://res.cloudinary.com/sguhbpc0/image/upload/f_auto,q_auto/v1/isole-digital-showroom/community-6",
  "/images/detail-back.png": "https://res.cloudinary.com/sguhbpc0/image/upload/f_auto,q_auto/v1/isole-digital-showroom/detail-back",
  "/images/detail-lifestyle.png": "https://res.cloudinary.com/sguhbpc0/image/upload/f_auto,q_auto/v1/isole-digital-showroom/detail-lifestyle",
  "/images/detail-texture.png": "https://res.cloudinary.com/sguhbpc0/image/upload/f_auto,q_auto/v1/isole-digital-showroom/detail-texture",
  "/images/editorial-story.png": "https://res.cloudinary.com/sguhbpc0/image/upload/f_auto,q_auto/v1/isole-digital-showroom/editorial-story",
  "/images/hero.png": "https://res.cloudinary.com/sguhbpc0/image/upload/f_auto,q_auto/v1/isole-digital-showroom/hero",
  "/images/isabella-reel-dsksenrjdso.jpg": "https://res.cloudinary.com/sguhbpc0/image/upload/f_auto,q_auto/v1/isole-digital-showroom/isabella-reel-dsksenrjdso",
  "/images/isabella-reel-durhgmnjtch.jpg": "https://res.cloudinary.com/sguhbpc0/image/upload/f_auto,q_auto/v1/isole-digital-showroom/isabella-reel-durhgmnjtch",
  "/images/isabella-reel-dwz4fbudgbk.jpg": "https://res.cloudinary.com/sguhbpc0/image/upload/f_auto,q_auto/v1/isole-digital-showroom/isabella-reel-dwz4fbudgbk",
  "/images/isabella-reel-dxhj5cydnqh.jpg": "https://res.cloudinary.com/sguhbpc0/image/upload/f_auto,q_auto/v1/isole-digital-showroom/isabella-reel-dxhj5cydnqh",
  "/images/isabella-reel-dxsbqtfdtu.jpg": "https://res.cloudinary.com/sguhbpc0/image/upload/f_auto,q_auto/v1/isole-digital-showroom/isabella-reel-dxsbqtfdtu",
  "/images/isabella-reel-dy-psx0ifrh.jpg": "https://res.cloudinary.com/sguhbpc0/image/upload/f_auto,q_auto/v1/isole-digital-showroom/isabella-reel-dy-psx0ifrh",
  "/images/isole-logo-wordmark.png": "https://res.cloudinary.com/sguhbpc0/image/upload/f_auto,q_auto/v1/isole-digital-showroom/isole-logo-wordmark",
  "/images/manifesto.png": "https://res.cloudinary.com/sguhbpc0/image/upload/f_auto,q_auto/v1/isole-digital-showroom/manifesto"
} as const

export type CloudinaryAssetPath = keyof typeof cloudinaryAssets

export function cloudinaryImage(path: string) {
  return cloudinaryAssets[path as CloudinaryAssetPath] ?? path
}
